CREATE TABLE cliente(
    CLIENTE_ID INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(30),
    ENDERECO VARCHAR(300) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(CLIENTE_ID)
);

CREATE TABLE conta(
    NUMERO_CONTA INTEGER NOT NULL,
    AGENCIA INTEGER NOT NULL,
    SENHA VARCHAR(6) NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    CONSTRAINT PK_CONTA PRIMARY KEY(NUMERO_CONTA));

CREATE TABLE produto_financeiro(
    PRODUTO_FINANCEIRO_ID INTEGER NOT NULL AUTO_INCREMENT,
    VALOR FLOAT,
    FK_NUMERO_CONTA INTEGER NOT NULL,
    FK_TIPO_PRODUTO_FINANCEIRO_ID INTEGER NOT NULL,
    CONSTRAINT PK_PRODUTO_FINANCEIERO PRIMARY KEY(PRODUTO_FINANCEIRO_ID)
);

CREATE TABLE tipo_produto_financeiro(
    TIPO_PRODUTO_FINANCEIRO_ID INTEGER NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_TIPO_PRODUTO_FINANCEIRO PRIMARY KEY (TIPO_PRODUTO_FINANCEIRO_ID)
);


ALTER TABLE conta ADD CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (FK_CLIENTE_ID) REFERENCES cliente(CLIENTE_ID);


ALTER TABLE produto_financeiro ADD CONSTRAINT FK_PRODUTO_FINANCEIRO_TIPO_PRODUTO_FINANCEIRO FOREIGN KEY (FK_TIPO_PRODUTO_FINANCEIRO_ID) REFERENCES tipo_produto_financeiro (TIPO_PRODUTO_FINANCEIRO_ID);

ALTER TABLE produto_financeiro ADD CONSTRAINT FK_PRODUTO_FINANCEIRO_CONTA FOREIGN KEY (FK_NUMERO_CONTA) REFERENCES conta(NUMERO_CONTA);
